import os

lines = []
lines.append('import React, { useState, useEffect } from "react"')
lines.append('import { Search, Download, Clock, CheckCircle, XCircle, Plus, X, PackageCheck } from "lucide-react"')
lines.append('import { COLORS, money, primaryBtnStyle, secondaryBtnStyle, iconBtnStyle, overlayStyle, modalStyle, fieldLabelStyle, inputStyle } from "../styles.js"')
lines.append('import { SectionHeader } from "./Shared.jsx"')
lines.append('import { api } from "../api.js"')
lines.append('import { downloadCSV } from "../csv.js"')
lines.append('')
lines.append('const FILTERS = [')
lines.append('  { id: "all", label: "All" },')
lines.append('  { id: "open", label: "Open" },')
lines.append('  { id: "received", label: "Received" },')
lines.append('  { id: "cancelled", label: "Cancelled" },')
lines.append(']')
lines.append('const META = {')
lines.append('  open: { label: "Open", color: COLORS.amber, icon: Clock },')
lines.append('  received: { label: "Received", color: COLORS.teal, icon: CheckCircle },')
lines.append('  cancelled: { label: "Cancelled", color: COLORS.rose, icon: XCircle },')
lines.append('}')
lines.append('')
lines.append('function Badge({ status }) {')
lines.append('  const m = META[status] || META.cancelled')
lines.append('  const I = m.icon')
lines.append('  return (')
lines.append('    <span style={{')
lines.append('      fontFamily: "Inter", fontSize: 11, fontWeight: 600,')
lines.append('      color: m.color, background: m.color + "18",')
lines.append('      padding: "3px 10px", borderRadius: 20,')
lines.append('      display: "inline-flex", alignItems: "center", gap: 4,')
lines.append('    }}>')
lines.append('      <I size={12} /> {m.label}')
lines.append('    </span>')
lines.append('  )')
lines.append('}')
lines.append('')
lines.append('function CreateOrderModal({ products, onClose, onCreate }) {')
lines.append('  const firstId = products.length > 0 ? products[0].id : ""')
lines.append('  const [productId, setProductId] = useState(firstId)')
lines.append('  const [qty, setQty] = useState(1)')
lines.append('  const [supplierName, setSupplierName] = useState("")')
lines.append('  const sel = products.find((p) => p.id === productId)')
lines.append('')
lines.append('  return (')
lines.append('    <div style={overlayStyle} onClick={onClose}>')
lines.append('      <div style={{ ...modalStyle, maxWidth: 420 }} onClick={(e) => e.stopPropagation()}>')
lines.append('        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>')
lines.append('          <h3 style={{ fontFamily: "\\\'Space Grotesk\\\', sans-serif", fontSize: 17, margin: 0 }}>Create Purchase Order</h3>')
lines.append('          <button onClick={onClose} style={iconBtnStyle}><X size={18} /></button>')
lines.append('        </div>')
lines.append('        <label style={{ ...fieldLabelStyle, marginBottom: 14 }}>')
lines.append('          Product')
lines.append('          <select value={productId} onChange={(e) => setProductId(e.target.value)} style={{ ...inputStyle, fontFamily: "Inter" }}>')
lines.append('            {products.map((p) => (')
lines.append('              <option key={p.id} value={p.id}>{p.name} ({p.sku})</option>')
lines.append('            ))}')
lines.append('          </select>')
lines.append('        </label>')
lines.append('        <label style={{ ...fieldLabelStyle, marginBottom: 14 }}>')
lines.append('          Supplier Name')
lines.append('          <input type="text" value={supplierName} onChange={(e) => setSupplierName(e.target.value)} placeholder="e.g. TZ Wholesale Ltd" style={inputStyle} />')
lines.append('        </label>')
lines.append('        <label style={{ ...fieldLabelStyle, marginBottom: 20 }}>')
lines.append('          Quantity')
lines.append('          <input type="number" min={1} value={qty} onChange={(e) => setQty(Math.max(1, Number(e.target.value)))} style={inputStyle} />')
lines.append('        </label>')
lines.append('        {sel && (')
lines.append('          <div style={{ fontFamily: "Inter", fontSize: 13, color: COLORS.sub, marginBottom: 16 }}>')
lines.append('            Estimated cost: {money(qty * sel.unitCost)}')
lines.append('          </div>')
lines.append('        )}')
lines.append('        <div style={{ display: "flex", justifyContent: "flex-end", gap: 10 }}>')
lines.append('          <button onClick={onClose} style={secondaryBtnStyle}>Cancel</button>')
lines.append('          <button onClick={() => onCreate(productId, qty, supplierName)} style={primaryBtnStyle} disabled={!productId}>')
lines.append('            Place order')
lines.append('          </button>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  )')
lines.append('}')
lines.append('')
lines.append('function ReceiveModal({ order, onClose, onReceive }) {')
lines.append('  const [units, setUnits] = useState(order.qty)')
lines.append('  return (')
lines.append('    <div style={overlayStyle} onClick={onClose}>')
lines.append('      <div style={{ ...modalStyle, maxWidth: 400 }} onClick={(e) => e.stopPropagation()}>')
lines.append('        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}>')
lines.append('          <h3 style={{ fontFamily: "\\\'Space Grotesk\\\', sans-serif", fontSize: 17, margin: 0 }}>Receive Shipment</h3>')
lines.append('          <button onClick={onClose} style={iconBtnStyle}><X size={18} /></button>')
lines.append('        </div>')
lines.append('        <p style={{ fontFamily: "Inter", fontSize: 13, color: COLORS.sub, marginTop: 0 }}>')
lines.append('          {order.productName} &middot; {order.qty} units ordered')
lines.append('        </p>')
lines.append('        <label style={fieldLabelStyle}>')
lines.append('          Units received')
lines.append('          <input type="number" min={0} value={units} onChange={(e) => setUnits(Number(e.target.value))} style={inputStyle} />')
lines.append('        </label>')
lines.append('        <div style={{ display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 20 }}>')
lines.append('          <button onClick={onClose} style={secondaryBtnStyle}>Cancel</button>')
lines.append('          <button onClick={() => onReceive(order.id, units)} style={primaryBtnStyle}>Add to stock</button>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  )')
lines.append('}')
lines.append('')
lines.append('export default function OrderHistory() {')
lines.append('  const [orders, setOrders] = useState([])')
lines.append('  const [loading, setLoading] = useState(true)')
lines.append('  const [search, setSearch] = useState("")')
lines.append('  const [filter, setFilter] = useState("all")')
lines.append('  const [error, setError] = useState(null)')
lines.append('  const [showCreateModal, setShowCreateModal] = useState(false)')
lines.append('  const [receiveFor, setReceiveFor] = useState(null)')
lines.append('  const [products, setProducts] = useState([])')
lines.append('')
lines.append('  const load = () => {')
lines.append('    setLoading(true)')
lines.append('    Promise.all([')
lines.append('      api.getOrders().then(setOrders),')
lines.append('      api.getProducts().then(setProducts),')
lines.append('    ]).catch((e) => setError(e.message)).finally(() => setLoading(false))')
lines.append('  }')
lines.append('')
lines.append('  useEffect(() => { load() }, [])')
lines.append('')
lines.append('  const handleCreate = async (productId, qty, supplierName) => {')
lines.append('    try {')
lines.append('      await api.createOrder(productId, qty, supplierName)')
lines.append('      setShowCreateModal(false)')
lines.append('      load()')
lines.append('    } catch (e) {')
lines.append('      setError(e.message)')
lines.append('    }')
lines.append('  }')
lines.append('')
lines.append('  const handleCancel = async (orderId) => {')
lines.append('    try {')
lines.append('      await api.cancelOrder(orderId)')
lines.append('      load()')
lines.append('    } catch (e) {')
lines.append('      setError(e.message)')
lines.append('    }')
lines.append('  }')
lines.append('')
lines.append('  const handleReceive = async (orderId, units) => {')
lines.append('    try {')
lines.append('      await api.receiveOrder(orderId, units)')
lines.append('      setReceiveFor(null)')
lines.append('      load()')
lines.append('    } catch (e) {')
lines.append('      setError(e.message)')
lines.append('    }')
lines.append('  }')
lines.append('')
lines.append('  const filteredOrders = orders.filter((o) => {')
lines.append('    if (filter !== "all" && o.status !== filter) return false')
lines.append('    if (search) {')
lines.append('      const q = search.toLowerCase()')
lines.append('      const nameMatch = (o.productName || "").toLowerCase().includes(q)')
lines.append('      const skuMatch = (o.productSku || "").toLowerCase().includes(q)')
lines.append('      const supplierMatch = (o.supplierName || "").toLowerCase().includes(q)')
lines.append('      if (!nameMatch && !skuMatch && !supplierMatch) return false')
lines.append('    }')
lines.append('    return true')
lines.append('  })')
lines.append('')
lines.append('  const exportCSV = () => {')
lines.append('    const h = ["Date Placed", "Product", "SKU", "Supplier", "Qty", "Status", "Date Received"]')
lines.append('    const r = filteredOrders.map((o) => [')
lines.append('      o.placedAt, o.productName || "---", o.productSku || "---",')
lines.append('      o.supplierName || "---", o.qty, o.status, o.receivedAt || "---",')
lines.append('    ])')
lines.append('    downloadCSV("orders-" + new Date().toISOString().slice(0, 10) + ".csv", [h, ...r])')
lines.append('  }')
lines.append('')
lines.append('  return (')
lines.append('    <div>')
lines.append('      <SectionHeader')
lines.append('        title="Purchase Order History"')
lines.append('        subtitle="All stock orders placed to suppliers."')
lines.append('        action={')
lines.append('          <div style={{ display: "flex", gap: 8 }}>')
lines.append('            <button onClick={exportCSV} disabled={filteredOrders.length === 0} style={secondaryBtnStyle}>')
lines.append('              <span style={{ display: "flex", alignItems: "center", gap: 6 }}><Download size={15} /> Export CSV</span>')
lines.append('            </button>')
lines.append('            <button onClick={() => setShowCreateModal(true)} style={primaryBtnStyle}>')
lines.append('              <span style={{ display: "flex", alignItems: "center", gap: 8 }}><Plus size={15} /> Create Purchase Order</span>')
lines.append('            </button>')
lines.append('          </div>')
lines.append('        }')
lines.append('      />')
lines.append('')
lines.append('      <div style={{ display: "flex", gap: 14, marginBottom: 18, flexWrap: "wrap" }}>')
lines.append('        <div style={{ background: COLORS.panel, border: "1px solid " + COLORS.line, borderRadius: 12, padding: "14px 18px", flex: 1, minWidth: 120 }}>')
lines.append('          <div style={{ fontFamily: "Inter", fontSize: 12, color: COLORS.sub, marginBottom: 4 }}>Total</div>')
lines.append('          <div style={{ fontFamily: "\\\'Space Grotesk\\\',sans-serif", fontSize: 22, fontWeight: 700, color: COLORS.ink }}>{orders.length}</div>')
lines.append('        </div>')
lines.append('        <div style={{ background: COLORS.panel, border: "1px solid " + COLORS.line, borderRadius: 12, padding: "14px 18px", flex: 1, minWidth: 120 }}>')
lines.append('          <div style={{ fontFamily: "Inter", fontSize: 12, color: COLORS.sub, marginBottom: 4 }}>Open</div>')
lines.append('          <div style={{ fontFamily: "\\\'Space Grotesk\\\',sans-serif", fontSize: 22, fontWeight: 700, color: COLORS.amber }}>{orders.filter((o) => o.status === "open").length}</div>')
lines.append('        </div>')
lines.append('        <div style={{ background: COLORS.panel, border: "1px solid " + COLORS.line, borderRadius: 12, padding: "14px 18px", flex: 1, minWidth: 120 }}>')
lines.append('          <div style={{ fontFamily: "Inter", fontSize: 12, color: COLORS.sub, marginBottom: 4 }}>Received</div>')
lines.append('          <div style={{ fontFamily: "\\\'Space Grotesk\\\',sans-serif", fontSize: 22, fontWeight: 700, color: COLORS.teal }}>{orders.filter((o) => o.status === "received").length}</div>')
lines.append('        </div>')
lines.append('        <div style={{ background: COLORS.panel, border: "1px solid " + COLORS.line, borderRadius: 12, padding: "14px 18px", flex: 1, minWidth: 120 }}>')
lines.append('          <div style={{ fontFamily: "Inter", fontSize: 12, color: COLORS.sub, marginBottom: 4 }}>Cancelled</div>')
lines.append('          <div style={{ fontFamily: "\\\'Space Grotesk\\\',sans-serif", fontSize: 22, fontWeight: 700, color: COLORS.rose }}>{orders.filter((o) => o.status === "cancelled").length}</div>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('')
lines.append('      <div style={{ display: "flex", gap: 10, alignItems: "center", marginBottom: 16, flexWrap: "wrap" }}>')
lines.append('        <div style={{ display: "flex", alignItems: "center", gap: 8, background: "#fff", border: "1px solid " + COLORS.line, borderRadius: 9, padding: "8px 12px", flex: 1, maxWidth: 320 }}>')
lines.append('          <Search size={15} color={COLORS.sub} />')
lines.append('          <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by name, SKU, or supplier"')
lines.append('            style={{ border: "none", outline: "none", fontFamily: "Inter", fontSize: 13.5, width: "100%" }} />')
lines.append('        </div>')
lines.append('        <div style={{ display: "flex", gap: 4 }}>')
lines.append('          {FILTERS.map((fi) => (')
lines.append('            <button key={fi.id} onClick={() => setFilter(fi.id)} style={{')
lines.append('              fontFamily: "Inter", fontSize: 12.5, fontWeight: filter === fi.id ? 600 : 400,')
lines.append('              padding: "6px 12px", borderRadius: 8, border: "1px solid " + COLORS.line,')
lines.append('              background: filter === fi.id ? COLORS.primary : "#fff",')
lines.append('              color: filter === fi.id ? "#fff" : COLORS.ink, cursor: "pointer",')
lines.append('            }}>')
lines.append('              {fi.label}')
lines.append('            </button>')
lines.append('          ))}')
lines.append('        </div>')
lines.append('      </div>')
lines.append('')
lines.append('      <div style={{ background: COLORS.panel, border: "1px solid " + COLORS.line, borderRadius: 14, overflow: "hidden" }}>')
lines.append('        <table style={{ width: "100%", borderCollapse: "collapse" }}>')
lines.append('          <thead>')
lines.append('            <tr>')
lines.append('              <th style={{ fontFamily: "Inter", fontSize: 12, fontWeight: 600, color: COLORS.sub, textAlign: "left", padding: "12px 16px", borderBottom: "1px solid " + COLORS.line }}>Date Placed</th>')
lines.append('              <th style={{ fontFamily: "Inter", fontSize: 12, fontWeight: 600, color: COLORS.sub, textAlign: "left", padding: "12px 16px", borderBottom: "1px solid " + COLORS.line }}>Product</th>')
lines.append('              <th style={{ fontFamily: "Inter", fontSize: 12, fontWeight: 600, color: COLORS.sub, textAlign: "left", padding: "12px 16px", borderBottom: "1px solid " + COLORS.line }}>SKU</th>')
lines.append('              <th style={{ fontFamily: "Inter", fontSize: 12, fontWeight: 600, color: COLORS.sub, textAlign: "left", padding: "12px 16px", borderBottom: "1px solid " + COLORS.line }}>Supplier</th>')
lines.append('              <th style={{ fontFamily: "Inter", fontSize: 12, fontWeight: 600, color: COLORS.sub, textAlign: "left", padding: "12px 16px", borderBottom: "1px solid " + COLORS.line }}>Qty</th>')
lines.append('              <th style={{ fontFamily: "Inter", fontSize: 12, fontWeight: 600, color: COLORS.sub, textAlign: "left", padding: "12px 16px", borderBottom: "1px solid " + COLORS.line }}>Status</th>')
lines.append('              <th style={{ fontFamily: "Inter", fontSize: 12, fontWeight: 600, color: COLORS.sub, textAlign: "left", padding: "12px 16px", borderBottom: "1px solid " + COLORS.line }}>Actions</th>')
lines.append('            </tr>')
lines.append('          </thead>')
lines.append('          <tbody>')
lines.append('            {loading ? (')
lines.append('              <tr><td colSpan={7} style={{ textAlign: "center", color: COLORS.sub, padding: 30, fontFamily: "Inter", fontSize: 13 }}>Loading...</td></tr>')
lines.append('            ) : filteredOrders.length === 0 ? (')
lines.append('              <tr><td colSpan={7} style={{ textAlign: "center", color: COLORS.sub, padding: 30, fontFamily: "Inter", fontSize: 13 }}>')
lines.append('                {search || filter !== "all" ? "No matches." : "No orders yet."}')
lines.append('              </td></tr>')
lines.append('            ) : filteredOrders.map((o) => (')
lines.append('              <tr key={o.id} style={{ borderBottom: "1px solid " + COLORS.line }}>')
lines.append('                <td style={{ fontFamily: "\\\'IBM Plex Mono\\\',monospace", fontSize: 12.5, color: COLORS.sub, whiteSpace: "nowrap", padding: "12px 16px" }}>')
lines.append('                  {new Date(o.placedAt).toLocaleString()}')
lines.append('                </td>')
lines.append('                <td style={{ fontWeight: 500, padding: "12px 16px", fontFamily: "Inter", fontSize: 13.5 }}>{o.productName || "---"}</td>')
lines.append('                <td style={{ fontFamily: "\\\'IBM Plex Mono\\\',monospace", fontSize: 12.5, color: COLORS.sub, padding: "12px 16px" }}>')
lines.append('                  {o.productSku || "---"}')
lines.append('                </td>')
lines.append('                <td style={{ fontFamily: "Inter", fontSize: 13, padding: "12px 16px" }}>')
lines.append('                  {o.supplierName || <span style={{ color: COLORS.sub, fontStyle: "italic" }}>N/A</span>}')
lines.append('                </td>')
lines.append('                <td style={{ fontFamily: "\\\'IBM Plex Mono\\\',monospace", fontWeight: 600, padding: "12px 16px" }}>{o.qty}</td>')
lines.append('                <td style={{ padding: "12px 16px" }}><Badge status={o.status} /></td>')
lines.append('                <td style={{ padding: "12px 16px" }}>')
lines.append('                  {o.status === "open" ? (')
lines.append('                    <div style={{ display: "flex", gap: 6 }}>')
lines.append('                      <button onClick={() => setReceiveFor(o)} style={{')
lines.append('                        ...secondaryBtnStyle, padding: "5px 10px", fontSize: 12,')
lines.append('                      }}>')
lines.append('                        <span style={{ display: "flex", alignItems: "center", gap: 4 }}>')
lines.append('                          <PackageCheck size={13} /> Receive')
lines.append('                        </span>')
lines.append('                      </button>')
lines.append('                      <button onClick={() => handleCancel(o.id)} style={{')
lines.append('                        ...secondaryBtnStyle, padding: "5px 10px", fontSize: 12, color: COLORS.rose,')
lines.append('                      }}>')
lines.append('                        <span style={{ display: "flex", alignItems: "center", gap: 4 }}>')
lines.append('                          <XCircle size={13} /> Cancel')
lines.append('                        </span>')
lines.append('                      </button>')
lines.append('                    </div>')
lines.append('                  ) : o.status === "received" ? (')
lines.append('                    <span style={{ fontFamily: "\\\'IBM Plex Mono\\\',monospace", fontSize: 12.5, color: COLORS.sub, display: "flex", alignItems: "center", gap: 6 }}>')
lines.append('                      <CheckCircle size={13} color={COLORS.teal} />')
lines.append('                      {o.receivedAt ? new Date(o.receivedAt).toLocaleString() : "Yes"}')
lines.append('                    </span>')
lines.append('                  ) : (')
lines.append('                    <span style={{ fontFamily: "\\\'IBM Plex Mono\\\',monospace", fontSize: 12.5, color: COLORS.sub, display: "flex", alignItems: "center", gap: 6 }}>')
lines.append('                      <XCircle size={13} color={COLORS.rose} />')
lines.append('                      Cancelled')
lines.append('                    </span>')
lines.append('                  )}')
lines.append('                </td>')
lines.append('              </tr>')
lines.append('            ))}')
lines.append('          </tbody>')
lines.append('        </table>')
lines.append('      </div>')
lines.append('')
lines.append('      {error && (')
lines.append('        <div style={{ background: COLORS.roseSoft, color: COLORS.rose, borderRadius: 8, padding: "10px 16px", fontFamily: "Inter", fontSize: 13, marginTop: 16 }}>')
lines.append('          {error}')
lines.append('        </div>')
lines.append('      )}')
lines.append('')
lines.append('      {showCreateModal && (')
lines.append('        <CreateOrderModal')
lines.append('          products={products}')
lines.append('          onClose={() => setShowCreateModal(false)}')
lines.append('          onCreate={handleCreate}')
lines.append('        />')
lines.append('      )}')
lines.append('')
lines.append('      {receiveFor && (')
lines.append('        <ReceiveModal')
lines.append('          order={receiveFor}')
lines.append('          onClose={() => setReceiveFor(null)}')
lines.append('          onReceive={handleReceive}')
lines.append('        />')
lines.append('      )}')
lines.append('    </div>')
lines.append('  )')
lines.append('}')
lines.append('')

content = "\n".join(lines)
# fix the escaped quotes back to proper JSX
content = content.replace("\\\'", "'")

path = os.path.join(os.environ.get('USERPROFILE', 'C:/Users/krypt'), 'Downloads', 'niz', 'stockline', 'client', 'src', 'components', 'OrderHistory.jsx')
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('Written to', path)
